from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BankSphere(object):
    def setupUi(self, BankSphere):
        BankSphere.setObjectName("BankSphere")
        BankSphere.resize(1200, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BankSphere.sizePolicy().hasHeightForWidth())
        BankSphere.setSizePolicy(sizePolicy)
        ###
        self.centralwidget = QtWidgets.QWidget(parent=BankSphere)
        self.centralwidget.setObjectName("centralwidget")
        ###
        self.homepage = QtWidgets.QFrame(parent=self.centralwidget)
        self.homepage.setEnabled(True)
        self.homepage.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.homepage.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.homepage.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.homepage.setObjectName("homepage")
        ###
        self.main_label = QtWidgets.QLabel(parent=self.homepage)
        self.main_label.setGeometry(QtCore.QRect(350, 80, 501, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(58)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.main_label.setFont(font)
        self.main_label.setObjectName("main_label")
        ###
        self.sub_label = QtWidgets.QLabel(parent=self.homepage)
        self.sub_label.setGeometry(QtCore.QRect(470, 180, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.sub_label.setFont(font)
        self.sub_label.setObjectName("sub_label")
        ###
        self.username_label = QtWidgets.QLabel(parent=self.homepage)
        self.username_label.setGeometry(QtCore.QRect(430, 270, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        ###
        self.username_entry = QtWidgets.QLineEdit(parent=self.homepage)
        self.username_entry.setGeometry(QtCore.QRect(560, 270, 250, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.username_entry.setFont(font)
        self.username_entry.setText("")
        self.username_entry.setFrame(True)
        self.username_entry.setObjectName("username_entry")
        ###
        self.password_label = QtWidgets.QLabel(parent=self.homepage)
        self.password_label.setGeometry(QtCore.QRect(430, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        ###
        self.password_entry = QtWidgets.QLineEdit(parent=self.homepage)
        self.password_entry.setGeometry(QtCore.QRect(560, 330, 250, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.password_entry.setFont(font)
        self.password_entry.setText("")
        self.password_entry.setFrame(True)
        self.password_entry.setObjectName("password_entry")
        self.password_entry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        ###
        self.line = QtWidgets.QFrame(parent=self.homepage)
        self.line.setGeometry(QtCore.QRect(350, 210, 491, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        ###
        self.login_btn = QtWidgets.QPushButton(parent=self.homepage)
        self.login_btn.setGeometry(QtCore.QRect(490, 390, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        ###
        self.line_2 = QtWidgets.QFrame(parent=self.homepage)
        self.line_2.setGeometry(QtCore.QRect(420, 450, 351, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        ###
        self.new_user_label = QtWidgets.QLabel(parent=self.homepage)
        self.new_user_label.setGeometry(QtCore.QRect(530, 500, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(15)
        self.new_user_label.setFont(font)
        self.new_user_label.setObjectName("new_user_label")
        ###
        self.register_btn = QtWidgets.QPushButton(parent=self.homepage)
        self.register_btn.setGeometry(QtCore.QRect(490, 540, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.register_btn.setFont(font)
        self.register_btn.setObjectName("register_btn")
        ###
        self.register_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.register_frame.setEnabled(True)
        self.register_frame.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.register_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.register_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.register_frame.setObjectName("register_frame")
        ###
        self.label_1 = QtWidgets.QLabel(parent=self.register_frame)
        self.label_1.setGeometry(QtCore.QRect(350, 80, 501, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(58)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        ###
        self.sub_label_register = QtWidgets.QLabel(parent=self.register_frame)
        self.sub_label_register.setGeometry(QtCore.QRect(470, 180, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.sub_label_register.setFont(font)
        self.sub_label_register.setObjectName("sub_label_register")
        ###
        self.line = QtWidgets.QFrame(parent=self.register_frame)
        self.line.setGeometry(QtCore.QRect(350, 210, 491, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        ###
        self.label = QtWidgets.QLabel(parent=self.register_frame)
        self.label.setGeometry(QtCore.QRect(370, 280, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        ###
        self.firstname_entry = QtWidgets.QLineEdit(parent=self.register_frame)
        self.firstname_entry.setGeometry(QtCore.QRect(570, 280, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.firstname_entry.setFont(font)
        self.firstname_entry.setText("")
        self.firstname_entry.setObjectName("firstname_entry")
        ###
        self.label_2 = QtWidgets.QLabel(parent=self.register_frame)
        self.label_2.setGeometry(QtCore.QRect(370, 330, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        ###
        self.lastname_entry = QtWidgets.QLineEdit(parent=self.register_frame)
        self.lastname_entry.setGeometry(QtCore.QRect(570, 330, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.lastname_entry.setFont(font)
        self.lastname_entry.setText("")
        self.lastname_entry.setObjectName("lastname_entry")
        ###
        self.label_3 = QtWidgets.QLabel(parent=self.register_frame)
        self.label_3.setGeometry(QtCore.QRect(370, 380, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        ###
        self.date_entry = QtWidgets.QDateEdit(parent=self.register_frame)
        self.date_entry.setGeometry(QtCore.QRect(570, 380, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.date_entry.setFont(font)
        self.date_entry.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 30), QtCore.QTime(23, 59, 59)))
        self.date_entry.setObjectName("date_entry")
        ###
        self.label_4 = QtWidgets.QLabel(parent=self.register_frame)
        self.label_4.setGeometry(QtCore.QRect(370, 430, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        ###
        self.username_register_entry = QtWidgets.QLineEdit(parent=self.register_frame)
        self.username_register_entry.setGeometry(QtCore.QRect(570, 430, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.username_register_entry.setFont(font)
        self.username_register_entry.setText("")
        self.username_register_entry.setObjectName("username_register_entry")
        ###
        self.generate_username_btn = QtWidgets.QPushButton(parent=self.register_frame)
        self.generate_username_btn.setGeometry(QtCore.QRect(830, 432, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.generate_username_btn.setFont(font)
        self.generate_username_btn.setObjectName("generate_username_btn")
        ###
        self.label_5 = QtWidgets.QLabel(parent=self.register_frame)
        self.label_5.setGeometry(QtCore.QRect(370, 480, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        ###
        self.password_register_entry = QtWidgets.QLineEdit(parent=self.register_frame)
        self.password_register_entry.setGeometry(QtCore.QRect(570, 480, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.password_register_entry.setFont(font)
        self.password_register_entry.setText("")
        self.password_register_entry.setObjectName("password_register_entry")
        ###
        self.register_form_btn = QtWidgets.QPushButton(parent=self.register_frame)
        self.register_form_btn.setGeometry(QtCore.QRect(530, 540, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.register_form_btn.setFont(font)
        self.register_form_btn.setObjectName("register_form_btn")
        ###
        self.loggedin_homepage = QtWidgets.QFrame(parent=self.centralwidget)
        self.loggedin_homepage.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.loggedin_homepage.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loggedin_homepage.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loggedin_homepage.setObjectName("loggedin_homepage")
        ###
        self.main_label_logged = QtWidgets.QLabel(parent=self.loggedin_homepage)
        self.main_label_logged.setGeometry(QtCore.QRect(350, 10, 501, 81))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(58)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.main_label_logged.setFont(font)
        self.main_label_logged.setObjectName("main_label_logged")
        ###
        self.sub_label_logged = QtWidgets.QLabel(parent=self.loggedin_homepage)
        self.sub_label_logged.setGeometry(QtCore.QRect(470, 90, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.sub_label_logged.setFont(font)
        self.sub_label_logged.setObjectName("sub_label_logged")
        ###
        self.line = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.line.setGeometry(QtCore.QRect(400, 120, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        ###
        self.tabs_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.tabs_frame.setGeometry(QtCore.QRect(10, 180, 211, 610))
        self.tabs_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tabs_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tabs_frame.setObjectName("tabs_frame")
        ###
        self.acc_info_btn = QtWidgets.QPushButton(parent=self.tabs_frame)
        self.acc_info_btn.setGeometry(QtCore.QRect(10, 10, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(15)
        self.acc_info_btn.setFont(font)
        self.acc_info_btn.setObjectName("acc_info_btn")
        ###
        self.transfer_btn = QtWidgets.QPushButton(parent=self.tabs_frame)
        self.transfer_btn.setGeometry(QtCore.QRect(10, 70, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(15)
        self.transfer_btn.setFont(font)
        self.transfer_btn.setObjectName("transfer_btn")
        ###
        self.transactionsbtn = QtWidgets.QPushButton(parent=self.tabs_frame)
        self.transactionsbtn.setGeometry(QtCore.QRect(10, 130, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(15)
        self.transactionsbtn.setFont(font)
        self.transactionsbtn.setObjectName("transactionsbtn")
        ###
        self.add_mon_btn = QtWidgets.QPushButton(parent=self.tabs_frame)
        self.add_mon_btn.setGeometry(QtCore.QRect(10, 190, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(15)
        self.add_mon_btn.setFont(font)
        self.add_mon_btn.setObjectName("add_mon_btn")
        ###
        self.profile_btn = QtWidgets.QPushButton(parent=self.tabs_frame)
        self.profile_btn.setGeometry(QtCore.QRect(10, 550, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(15)
        self.profile_btn.setFont(font)
        self.profile_btn.setObjectName("profile_btn")
        ###
        self.profile_info = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.profile_info.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.profile_info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.profile_info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.profile_info.setObjectName("profile_info")
        ###
        self.P_icon = QtWidgets.QLabel(parent=self.profile_info)
        self.P_icon.setGeometry(QtCore.QRect(440, 40, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.P_icon.setFont(font)
        self.P_icon.setText("")
        self.P_icon.setPixmap(QtGui.QPixmap("files_icon/icon.jpg"))
        self.P_icon.setScaledContents(True)
        self.P_icon.setObjectName("P_icon")
        ###
        self.p_proicon = QtWidgets.QLabel(parent=self.profile_info)
        self.p_proicon.setGeometry(QtCore.QRect(430, 170, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.p_proicon.setFont(font)
        self.p_proicon.setObjectName("p_proicon")
        ###
        self.p_usn = QtWidgets.QLabel(parent=self.profile_info)
        self.p_usn.setGeometry(QtCore.QRect(190, 250, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_usn.setFont(font)
        self.p_usn.setObjectName("p_usn")
        ###
        self.p_fn = QtWidgets.QLabel(parent=self.profile_info)
        self.p_fn.setGeometry(QtCore.QRect(190, 300, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_fn.setFont(font)
        self.p_fn.setObjectName("p_fn")
        ###
        self.p_ln = QtWidgets.QLabel(parent=self.profile_info)
        self.p_ln.setGeometry(QtCore.QRect(190, 350, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_ln.setFont(font)
        self.p_ln.setObjectName("p_ln")
        ###
        self.p_db = QtWidgets.QLabel(parent=self.profile_info)
        self.p_db.setGeometry(QtCore.QRect(190, 400, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_db.setFont(font)
        self.p_db.setObjectName("p_db")
        ###
        self.p_adr = QtWidgets.QLabel(parent=self.profile_info)
        self.p_adr.setGeometry(QtCore.QRect(190, 450, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_adr.setFont(font)
        self.p_adr.setObjectName("p_adr")
        ###
        self.p_phnno = QtWidgets.QLabel(parent=self.profile_info)
        self.p_phnno.setGeometry(QtCore.QRect(190, 500, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_phnno.setFont(font)
        self.p_phnno.setObjectName("p_phnno")
        ###
        self.p_em = QtWidgets.QLabel(parent=self.profile_info)
        self.p_em.setGeometry(QtCore.QRect(190, 550, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p_em.setFont(font)
        self.p_em.setObjectName("p_em")
        ###
        self.p_username = QtWidgets.QLabel(parent=self.profile_info)
        self.p_username.setGeometry(QtCore.QRect(470, 250, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.p_username.setFont(font)
        self.p_username.setObjectName("p_username")
        ###
        self.p_firstname = QtWidgets.QLabel(parent=self.profile_info)
        self.p_firstname.setGeometry(QtCore.QRect(470, 300, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.p_firstname.setFont(font)
        self.p_firstname.setObjectName("p_firstname")
        ###
        self.p_lastname = QtWidgets.QLabel(parent=self.profile_info)
        self.p_lastname.setGeometry(QtCore.QRect(470, 350, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.p_lastname.setFont(font)
        self.p_lastname.setObjectName("p_lastname")
        ###
        self.p_dob = QtWidgets.QLabel(parent=self.profile_info)
        self.p_dob.setGeometry(QtCore.QRect(470, 400, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.p_dob.setFont(font)
        self.p_dob.setObjectName("p_dob")
        ###
        self.p_address = QtWidgets.QLabel(parent=self.profile_info)
        self.p_address.setGeometry(QtCore.QRect(470, 450, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.p_address.setFont(font)
        self.p_address.setObjectName("p_address")
        ###
        self.p_phonenum = QtWidgets.QLabel(parent=self.profile_info)
        self.p_phonenum.setGeometry(QtCore.QRect(470, 500, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.p_phonenum.setFont(font)
        self.p_phonenum.setObjectName("p_phonenum")
        ###
        self.p_email = QtWidgets.QLabel(parent=self.profile_info)
        self.p_email.setGeometry(QtCore.QRect(470, 550, 350, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(True)
        self.p_email.setFont(font)
        self.p_email.setObjectName("p_email")
        ### 
        self.p_edit_profile_btn = QtWidgets.QPushButton(parent=self.profile_info)
        self.p_edit_profile_btn.setGeometry(QtCore.QRect(350, 610, 150, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(13)
        self.p_edit_profile_btn.setFont(font)
        self.p_edit_profile_btn.setObjectName("p_edit_profile_btn")
        ###
        self.transfer_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.transfer_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.transfer_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.transfer_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.transfer_frame.setObjectName("transfer_frame")
        ###
        self.tr_b = QtWidgets.QLabel(parent=self.transfer_frame)
        self.tr_b.setGeometry(QtCore.QRect(290, 230, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(25)
        self.tr_b.setFont(font)
        self.tr_b.setObjectName("tr_b")
        ###
        self.tr_bank = QtWidgets.QComboBox(parent=self.transfer_frame)
        self.tr_bank.setGeometry(QtCore.QRect(510, 230, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        font.setWeight(50)
        self.tr_bank.setFont(font)
        self.tr_bank.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tr_bank.setAutoFillBackground(False)
        self.tr_bank.setCurrentText("")
        self.tr_bank.setObjectName("tr_bank")
        ###
        self.tr_cont = QtWidgets.QPushButton(parent=self.transfer_frame)
        self.tr_cont.setGeometry(QtCore.QRect(450, 490, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.tr_cont.setFont(font)
        self.tr_cont.setObjectName("tr_cont")
        ###
        self.tr_s = QtWidgets.QLabel(parent=self.transfer_frame)
        self.tr_s.setGeometry(QtCore.QRect(140, 290, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(25)
        self.tr_s.setFont(font)
        self.tr_s.setObjectName("tr_s")
        ###
        self.tr_r = QtWidgets.QLabel(parent=self.transfer_frame)
        self.tr_r.setGeometry(QtCore.QRect(110, 350, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(25)
        self.tr_r.setFont(font)
        self.tr_r.setObjectName("tr_r")
        ###
        self.tr_a = QtWidgets.QLabel(parent=self.transfer_frame)
        self.tr_a.setGeometry(QtCore.QRect(340, 410, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(25)
        self.tr_a.setFont(font)
        self.tr_a.setObjectName("tr_a")
        ###
        self.tr_sender_acc = QtWidgets.QComboBox(parent=self.transfer_frame)
        self.tr_sender_acc.setGeometry(QtCore.QRect(510, 290, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        font.setWeight(50)
        self.tr_sender_acc.setFont(font)
        self.tr_sender_acc.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tr_sender_acc.setAutoFillBackground(False)
        self.tr_sender_acc.setCurrentText("")
        self.tr_sender_acc.setObjectName("tr_sender_acc")
        ###
        self.tr_reciever_acc = QtWidgets.QLineEdit(parent=self.transfer_frame)
        self.tr_reciever_acc.setGeometry(QtCore.QRect(510, 350, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        self.tr_reciever_acc.setFont(font)
        self.tr_reciever_acc.setText("")
        self.tr_reciever_acc.setObjectName("tr_reciever_acc")
        ###
        self.tr_amt = QtWidgets.QLineEdit(parent=self.transfer_frame)
        self.tr_amt.setGeometry(QtCore.QRect(510, 410, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        self.tr_amt.setFont(font)
        self.tr_amt.setText("")
        self.tr_amt.setObjectName("tr_amt")
        ###
        self.tr_logo = QtWidgets.QLabel(parent=self.transfer_frame)
        self.tr_logo.setGeometry(QtCore.QRect(410, 20, 161, 171))
        self.tr_logo.setText("")
        self.tr_logo.setPixmap(QtGui.QPixmap("files_icon/transfer_logo.png"))
        self.tr_logo.setScaledContents(True)
        self.tr_logo.setObjectName("tr_logo")
        ###
        self.tr_list_acc = QtWidgets.QPushButton(parent=self.transfer_frame)
        self.tr_list_acc.setGeometry(QtCore.QRect(800, 235, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.tr_list_acc.setFont(font)
        self.tr_list_acc.setObjectName("tr_list_acc")
        ###
        self.tr_confirm_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.tr_confirm_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.tr_confirm_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tr_confirm_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tr_confirm_frame.setObjectName("tr_confirm_frame")
        ###
        self.trc_qr = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_qr.setGeometry(QtCore.QRect(70, 250, 341, 311))
        self.trc_qr.setText("")
        self.trc_qr.setPixmap(QtGui.QPixmap("files_icon/my_qr.jpg"))
        self.trc_qr.setScaledContents(True)
        self.trc_qr.setObjectName("trc_qr")
        ###
        self.trc_fr = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_fr.setGeometry(QtCore.QRect(10, 80, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(23)
        self.trc_fr.setFont(font)
        self.trc_fr.setObjectName("trc_fr")
        ###
        self.trc_t = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_t.setGeometry(QtCore.QRect(560, 80, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(23)
        self.trc_t.setFont(font)
        self.trc_t.setObjectName("trc_t")
        ###
        self.trc_a = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_a.setGeometry(QtCore.QRect(340, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(23)
        self.trc_a.setFont(font)
        self.trc_a.setObjectName("trc_a")
        ###
        self.trc_sender_name = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_sender_name.setGeometry(QtCore.QRect(120, 80, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(23)
        font.setItalic(True)
        self.trc_sender_name.setFont(font)
        self.trc_sender_name.setText("")
        self.trc_sender_name.setObjectName("trc_sender_name")
        ###
        self.trc_sender_acc = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_sender_acc.setGeometry(QtCore.QRect(120, 120, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(10)
        self.trc_sender_acc.setFont(font)
        self.trc_sender_acc.setText("")
        self.trc_sender_acc.setObjectName("trc_sender_acc")
        ###
        self.trc_reciever_name = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_reciever_name.setGeometry(QtCore.QRect(630, 80, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(23)
        font.setItalic(True)
        self.trc_reciever_name.setFont(font)
        self.trc_reciever_name.setText("")
        self.trc_reciever_name.setObjectName("trc_reciever_name")
        ###
        self.trc_reciever_acc = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_reciever_acc.setGeometry(QtCore.QRect(630, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(10)
        self.trc_reciever_acc.setFont(font)
        self.trc_reciever_acc.setText("")
        self.trc_reciever_acc.setObjectName("trc_reciever_acc")
        ###
        self.trc_amt = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_amt.setGeometry(QtCore.QRect(480, 160, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(23)
        font.setItalic(True)
        self.trc_amt.setFont(font)
        self.trc_amt.setText("")
        self.trc_amt.setObjectName("trc_amt")
        ###
        self.trc_or = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_or.setGeometry(QtCore.QRect(460, 380, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(23)
        self.trc_or.setFont(font)
        self.trc_or.setObjectName("trc_or")
        ###
        self.trc_cancel = QtWidgets.QPushButton(parent=self.tr_confirm_frame)
        self.trc_cancel.setGeometry(QtCore.QRect(440, 610, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(15)
        self.trc_cancel.setFont(font)
        self.trc_cancel.setObjectName("trc_cancel")
        ###
        self.trc_ep = QtWidgets.QLabel(parent=self.tr_confirm_frame)
        self.trc_ep.setGeometry(QtCore.QRect(570, 380, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(23)
        self.trc_ep.setFont(font)
        self.trc_ep.setObjectName("trc_ep")
        ###
        self.trc_pin_entry = QtWidgets.QLineEdit(parent=self.tr_confirm_frame)
        self.trc_pin_entry.setGeometry(QtCore.QRect(740, 380, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.trc_pin_entry.setFont(font)
        self.trc_pin_entry.setText("")
        self.trc_pin_entry.setObjectName("trc_pin_entry")
        ###
        self.trc_line = QtWidgets.QFrame(parent=self.tr_confirm_frame)
        self.trc_line.setGeometry(QtCore.QRect(40, 220, 871, 16))
        self.trc_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.trc_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.trc_line.setObjectName("trc_line")
        ###
        self.trc_line_2 = QtWidgets.QFrame(parent=self.tr_confirm_frame)
        self.trc_line_2.setGeometry(QtCore.QRect(40, 30, 871, 16))
        self.trc_line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.trc_line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.trc_line_2.setObjectName("trc_line_2")
        ###
        self.trc_verify = QtWidgets.QPushButton(parent=self.tr_confirm_frame)
        self.trc_verify.setGeometry(QtCore.QRect(660, 440, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(15)
        self.trc_verify.setFont(font)
        self.trc_verify.setObjectName("trc_verify")
        ###
        self.trc_line_3 = QtWidgets.QFrame(parent=self.tr_confirm_frame)
        self.trc_line_3.setGeometry(QtCore.QRect(40, 590, 871, 16))
        self.trc_line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.trc_line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.trc_line_3.setObjectName("trc_line_3")
        ###
        self.tr_recipt_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.tr_recipt_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.tr_recipt_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tr_recipt_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tr_recipt_frame.setObjectName("tr_recipt_frame")
        ###
        self.tr_rec_logo = QtWidgets.QLabel(parent=self.tr_recipt_frame)
        self.tr_rec_logo.setGeometry(QtCore.QRect(320, 90, 271, 251))
        self.tr_rec_logo.setText("")
        self.tr_rec_logo.setPixmap(QtGui.QPixmap("files_icon/check_logo.jpg"))
        self.tr_rec_logo.setScaledContents(True)
        self.tr_rec_logo.setObjectName("tr_rec_logo")
        ###
        self.tr_rec_sd = QtWidgets.QLabel(parent=self.tr_recipt_frame)
        self.tr_rec_sd.setGeometry(QtCore.QRect(250, 380, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.tr_rec_sd.setFont(font)
        self.tr_rec_sd.setObjectName("tr_rec_sd")
        ###
        self.tr_rec_ti = QtWidgets.QLabel(parent=self.tr_recipt_frame)
        self.tr_rec_ti.setGeometry(QtCore.QRect(330, 490, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.tr_rec_ti.setFont(font)
        self.tr_rec_ti.setObjectName("tr_rec_ti")
        ###
        self.tr_rec_trans_id = QtWidgets.QLabel(parent=self.tr_recipt_frame)
        self.tr_rec_trans_id.setGeometry(QtCore.QRect(460, 490, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.tr_rec_trans_id.setFont(font)
        self.tr_rec_trans_id.setObjectName("tr_rec_trans_id")
        ###
        self.tr_rec_print = QtWidgets.QPushButton(parent=self.tr_recipt_frame)
        self.tr_rec_print.setGeometry(QtCore.QRect(330, 540, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.tr_rec_print.setFont(font)
        self.tr_rec_print.setObjectName("tr_rec_print")
        ###
        self.tr_rec_home = QtWidgets.QPushButton(parent=self.tr_recipt_frame)
        self.tr_rec_home.setGeometry(QtCore.QRect(460, 540, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.tr_rec_home.setFont(font)
        self.tr_rec_home.setObjectName("tr_rec_home")
        ###
        self.ai_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.ai_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.ai_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ai_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ai_frame.setObjectName("ai_frame")
        ###
        self.ai_acc_labels = QtWidgets.QLabel(parent=self.ai_frame)
        self.ai_acc_labels.setGeometry(QtCore.QRect(360, 20, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        self.ai_acc_labels.setFont(font)
        self.ai_acc_labels.setObjectName("ai_acc_labels")
        ###
        self.ai_add_acc_btn = QtWidgets.QPushButton(parent=self.ai_frame)
        self.ai_add_acc_btn.setGeometry(QtCore.QRect(420, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.ai_add_acc_btn.setFont(font)
        self.ai_add_acc_btn.setObjectName("ai_add_acc_btn")
        ###
        self.ai_table = QtWidgets.QTableWidget(parent=self.ai_frame)
        self.ai_table.setGeometry(QtCore.QRect(10, 130, 940, 470))
        self.ai_table.setObjectName("ai_table")
        self.ai_table.setColumnCount(5)
        self.ai_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ai_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ai_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ai_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ai_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ai_table.setHorizontalHeaderItem(4, item)
        ###
        header_font = QtGui.QFont('Lucida Bright', 12, QtGui.QFont.Weight.Bold)
        self.ai_table.horizontalHeader().setFont(header_font)
        data_font = QtGui.QFont('Lucida Bright', 12, QtGui.QFont.Weight.Normal)
        self.ai_table.setFont(data_font)
        ###
        self.ai_table.setColumnWidth(0, 90)
        self.ai_table.setColumnWidth(1, 210) 
        self.ai_table.setColumnWidth(2, 210)  
        self.ai_table.setColumnWidth(3, 210)  
        self.ai_table.setColumnWidth(4, 180) 
        ###
        self.ai_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.ai_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection) 
        ###
        self.ai_check_bal_btn = QtWidgets.QPushButton(parent=self.ai_frame)
        self.ai_check_bal_btn.setGeometry(QtCore.QRect(420, 610, 125, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.ai_check_bal_btn.setFont(font)
        self.ai_check_bal_btn.setObjectName("ai_check_bal_btn")
        ###
        self.ai_create_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.ai_create_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.ai_create_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ai_create_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ai_create_frame.setObjectName("ai_create_frame")
        ###
        self.ai_cr_label = QtWidgets.QLabel(parent=self.ai_create_frame)
        self.ai_cr_label.setGeometry(QtCore.QRect(360, 40, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(22)
        self.ai_cr_label.setFont(font)
        self.ai_cr_label.setObjectName("ai_cr_label")
        ###
        self.ai_cr_line = QtWidgets.QFrame(parent=self.ai_create_frame)
        self.ai_cr_line.setGeometry(QtCore.QRect(330, 70, 291, 20))
        self.ai_cr_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.ai_cr_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.ai_cr_line.setObjectName("ai_cr_line")
        ###
        self.ai_cr_b = QtWidgets.QLabel(parent=self.ai_create_frame)
        self.ai_cr_b.setGeometry(QtCore.QRect(280, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cr_b.setFont(font)
        self.ai_cr_b.setObjectName("ai_cr_b")
        ###
        self.ai_cr_bank = QtWidgets.QComboBox(parent=self.ai_create_frame)
        self.ai_cr_bank.setGeometry(QtCore.QRect(490, 150, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        font.setWeight(50)
        self.ai_cr_bank.setFont(font)
        self.ai_cr_bank.setObjectName("ai_cr_bank")
        ###
        self.ai_cr_at = QtWidgets.QLabel(parent=self.ai_create_frame)
        self.ai_cr_at.setGeometry(QtCore.QRect(180, 210, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cr_at.setFont(font)
        self.ai_cr_at.setObjectName("ai_cr_at")
        ###
        self.ai_cr_type = QtWidgets.QComboBox(parent=self.ai_create_frame)
        self.ai_cr_type.setGeometry(QtCore.QRect(490, 210, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        font.setWeight(50)
        self.ai_cr_type.setFont(font)
        self.ai_cr_type.setObjectName("ai_cr_type")
        ###
        self.ai_cr_p = QtWidgets.QLabel(parent=self.ai_create_frame)
        self.ai_cr_p.setGeometry(QtCore.QRect(190, 270, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cr_p.setFont(font)
        self.ai_cr_p.setObjectName("ai_cr_p")
        ###
        self.ai_cr_pin = QtWidgets.QLineEdit(parent=self.ai_create_frame)
        self.ai_cr_pin.setGeometry(QtCore.QRect(490, 270, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        font.setWeight(50)
        self.ai_cr_pin.setFont(font)
        self.ai_cr_pin.setObjectName("ai_cr_pin")
        ###
        self.ai_cr_btn = QtWidgets.QPushButton(parent=self.ai_create_frame)
        self.ai_cr_btn.setGeometry(QtCore.QRect(440, 350, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.ai_cr_btn.setFont(font)
        self.ai_cr_btn.setObjectName("ai_cr_btn")
        ###
        self.ai_cbal_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.ai_cbal_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.ai_cbal_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ai_cbal_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ai_cbal_frame.setObjectName("ai_cbal_frame")
        ###
        self.ai_cbal_label = QtWidgets.QLabel(parent=self.ai_cbal_frame)
        self.ai_cbal_label.setGeometry(QtCore.QRect(310, 40, 331, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(22)
        self.ai_cbal_label.setFont(font)
        self.ai_cbal_label.setObjectName("ai_cbal_label")
        ###
        self.ai_cbal_line = QtWidgets.QFrame(parent=self.ai_cbal_frame)
        self.ai_cbal_line.setGeometry(QtCore.QRect(330, 70, 291, 20))
        self.ai_cbal_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.ai_cbal_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.ai_cbal_line.setObjectName("ai_cbal_line")
        ###
        self.ai_cbal_b = QtWidgets.QLabel(parent=self.ai_cbal_frame)
        self.ai_cbal_b.setGeometry(QtCore.QRect(280, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cbal_b.setFont(font)
        self.ai_cbal_b.setObjectName("ai_cbal_b")
        ###
        self.ai_cbal_bank = QtWidgets.QComboBox(parent=self.ai_cbal_frame)
        self.ai_cbal_bank.setGeometry(QtCore.QRect(490, 150, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cbal_bank.setFont(font)
        self.ai_cbal_bank.setObjectName("ai_cbal_bank")
        ###
        self.ai_cbal_an = QtWidgets.QLabel(parent=self.ai_cbal_frame)
        self.ai_cbal_an.setGeometry(QtCore.QRect(210, 210, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cbal_an.setFont(font)
        self.ai_cbal_an.setObjectName("ai_cbal_an")
        ###
        self.ai_cbal_accnum = QtWidgets.QComboBox(parent=self.ai_cbal_frame)
        self.ai_cbal_accnum.setGeometry(QtCore.QRect(490, 210, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cbal_accnum.setFont(font)
        self.ai_cbal_accnum.setObjectName("ai_cbal_accnum")
        ###
        self.ai_cbal_list_acc = QtWidgets.QPushButton(parent=self.ai_cbal_frame)
        self.ai_cbal_list_acc.setGeometry(QtCore.QRect(725, 150, 130, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.ai_cbal_list_acc.setFont(font)
        self.ai_cbal_list_acc.setObjectName("ai_cbal_list_acc")
        ###
        self.ai_cbal_btn = QtWidgets.QPushButton(parent=self.ai_cbal_frame)
        self.ai_cbal_btn.setGeometry(QtCore.QRect(410, 340, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.ai_cbal_btn.setFont(font)
        self.ai_cbal_btn.setObjectName("ai_cbal_btn")
        ###
        self.ai_cbal_cb = QtWidgets.QLabel(parent=self.ai_cbal_frame)
        self.ai_cbal_cb.setGeometry(QtCore.QRect(240, 400, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        self.ai_cbal_cb.setFont(font)
        self.ai_cbal_cb.setObjectName("ai_cbal_cb")
        ###
        self.ai_cbal_bal = QtWidgets.QLabel(parent=self.ai_cbal_frame)
        self.ai_cbal_bal.setGeometry(QtCore.QRect(480, 400, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        self.ai_cbal_bal.setFont(font)
        self.ai_cbal_bal.setObjectName("ai_cbal_bal")
        ###
        self.ai_cbal_p = QtWidgets.QLabel(parent=self.ai_cbal_frame)
        self.ai_cbal_p.setGeometry(QtCore.QRect(270, 270, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cbal_p.setFont(font)
        self.ai_cbal_p.setObjectName("ai_cbal_p")
        ###
        self.ai_cbal_pin = QtWidgets.QLineEdit(parent=self.ai_cbal_frame)
        self.ai_cbal_pin.setGeometry(QtCore.QRect(490, 270, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.ai_cbal_pin.setFont(font)
        self.ai_cbal_pin.setText("")
        self.ai_cbal_pin.setObjectName("ai_cbal_pin")
        ###
        self.admin_login_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.admin_login_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.admin_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_login_frame.setObjectName("admin_login_frame")
        ###
        self.admin_label = QtWidgets.QLabel(parent=self.admin_login_frame)
        self.admin_label.setGeometry(QtCore.QRect(370, 110, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(25)
        self.admin_label.setFont(font)
        self.admin_label.setObjectName("admin_label")
        ###
        self.admin_line = QtWidgets.QFrame(parent=self.admin_login_frame)
        self.admin_line.setGeometry(QtCore.QRect(280, 160, 411, 20))
        self.admin_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.admin_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.admin_line.setObjectName("admin_line")
        ###
        self.admin_user = QtWidgets.QLineEdit(parent=self.admin_login_frame)
        self.admin_user.setGeometry(QtCore.QRect(470, 200, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.admin_user.setFont(font)
        self.admin_user.setText("")
        self.admin_user.setFrame(True)
        self.admin_user.setObjectName("admin_user")
        ###
        self.admin_username = QtWidgets.QLabel(parent=self.admin_login_frame)
        self.admin_username.setGeometry(QtCore.QRect(310, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.admin_username.setFont(font)
        self.admin_username.setObjectName("admin_username")
        ###
        self.admin_password = QtWidgets.QLineEdit(parent=self.admin_login_frame)
        self.admin_password.setGeometry(QtCore.QRect(470, 260, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.admin_password.setFont(font)
        self.admin_password.setText("")
        self.admin_password.setFrame(True)
        self.admin_password.setObjectName("admin_password")
        ###
        self.admin_pass = QtWidgets.QLabel(parent=self.admin_login_frame)
        self.admin_pass.setGeometry(QtCore.QRect(310, 260, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.admin_pass.setFont(font)
        self.admin_pass.setObjectName("admin_pass")
        ###
        self.admin_login_btn = QtWidgets.QPushButton(parent=self.admin_login_frame)
        self.admin_login_btn.setGeometry(QtCore.QRect(370, 330, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.admin_login_btn.setFont(font)
        self.admin_login_btn.setObjectName("admin_login_btn")
        ###
        self.add_mon_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.add_mon_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.add_mon_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.add_mon_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.add_mon_frame.setObjectName("add_mon_frame")
        ###
        self.add_mon_lab = QtWidgets.QLabel(parent=self.add_mon_frame)
        self.add_mon_lab.setGeometry(QtCore.QRect(390, 40, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(25)
        self.add_mon_lab.setFont(font)
        self.add_mon_lab.setObjectName("add_mon_lab")
        ###
        self.add_mon_sub = QtWidgets.QLabel(parent=self.add_mon_frame)
        self.add_mon_sub.setGeometry(QtCore.QRect(390, 90, 191, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        self.add_mon_sub.setFont(font)
        self.add_mon_sub.setObjectName("add_mon_sub")
        ###
        self.add_mon_bank = QtWidgets.QComboBox(parent=self.add_mon_frame)
        self.add_mon_bank.setGeometry(QtCore.QRect(470, 190, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_mon_bank.setFont(font)
        self.add_mon_bank.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.add_mon_bank.setAutoFillBackground(False)
        self.add_mon_bank.setCurrentText("")
        self.add_mon_bank.setObjectName("add_mon_bank")
        ###
        self.add_mon_b = QtWidgets.QLabel(parent=self.add_mon_frame)
        self.add_mon_b.setGeometry(QtCore.QRect(290, 200, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(19)
        self.add_mon_b.setFont(font)
        self.add_mon_b.setObjectName("add_mon_b")
        ###
        self.add_mon_lis_acc = QtWidgets.QPushButton(parent=self.add_mon_frame)
        self.add_mon_lis_acc.setGeometry(QtCore.QRect(760, 190, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.add_mon_lis_acc.setFont(font)
        self.add_mon_lis_acc.setObjectName("add_mon_lis_acc")
        ###
        self.add_mon_accnum = QtWidgets.QComboBox(parent=self.add_mon_frame)
        self.add_mon_accnum.setGeometry(QtCore.QRect(470, 250, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.add_mon_accnum.setFont(font)
        self.add_mon_accnum.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.add_mon_accnum.setAutoFillBackground(False)
        self.add_mon_accnum.setCurrentText("")
        self.add_mon_accnum.setObjectName("add_mon_accnum")
        ###
        self.add_mon_acc = QtWidgets.QLabel(parent=self.add_mon_frame)
        self.add_mon_acc.setGeometry(QtCore.QRect(230, 255, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.add_mon_acc.setFont(font)
        self.add_mon_acc.setObjectName("add_mon_acc")
        ###
        self.add_mon_am = QtWidgets.QLabel(parent=self.add_mon_frame)
        self.add_mon_am.setGeometry(QtCore.QRect(240, 315, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.add_mon_am.setFont(font)
        self.add_mon_am.setObjectName("add_mon_am")
        ###
        self.add_mon_amt = QtWidgets.QLineEdit(parent=self.add_mon_frame)
        self.add_mon_amt.setGeometry(QtCore.QRect(470, 310, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.add_mon_amt.setFont(font)
        self.add_mon_amt.setObjectName("add_mon_amt")
        ###
        self.add_mon_add_btn = QtWidgets.QPushButton(parent=self.add_mon_frame)
        self.add_mon_add_btn.setGeometry(QtCore.QRect(390, 390, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.add_mon_add_btn.setFont(font)
        self.add_mon_add_btn.setObjectName("add_mon_add_btn")
        ###
        self.transaction_frame = QtWidgets.QFrame(parent=self.loggedin_homepage)
        self.transaction_frame.setGeometry(QtCore.QRect(230, 140, 961, 651))
        self.transaction_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.transaction_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.transaction_frame.setObjectName("transaction_frame")
        self.trans_bank_opt = QtWidgets.QRadioButton(parent=self.transaction_frame)
        self.trans_bank_opt.setGeometry(QtCore.QRect(280, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.trans_bank_opt.setFont(font)
        self.trans_bank_opt.setObjectName("trans_bank_opt")
        self.trans_accnum_opt = QtWidgets.QRadioButton(parent=self.transaction_frame)
        self.trans_accnum_opt.setGeometry(QtCore.QRect(490, 30, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.trans_accnum_opt.setFont(font)
        self.trans_accnum_opt.setObjectName("trans_accnum_opt")
        self.trans_all_opt = QtWidgets.QRadioButton(parent=self.transaction_frame)
        self.trans_all_opt.setGeometry(QtCore.QRect(180, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.trans_all_opt.setFont(font)
        self.trans_all_opt.setObjectName("trans_all_opt")
        self.trans_retrive_tbn = QtWidgets.QPushButton(parent=self.transaction_frame)
        self.trans_retrive_tbn.setGeometry(QtCore.QRect(700, 90, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.trans_retrive_tbn.setFont(font)
        self.trans_retrive_tbn.setObjectName("trans_retrive_tbn")
        self.trans_table = QtWidgets.QTableWidget(parent=self.transaction_frame)
        self.trans_table.setGeometry(QtCore.QRect(10, 160, 941, 481))
        self.trans_table.setObjectName("trans_table")
        self.trans_table.setColumnCount(5)
        self.trans_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.trans_table.setHorizontalHeaderItem(4, item)

        self.trans_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.trans_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)

        header_font = QtGui.QFont('Lucida Bright', 12, QtGui.QFont.Weight.Bold)
        self.trans_table.horizontalHeader().setFont(header_font)
        data_font = QtGui.QFont('Lucida Bright', 12, QtGui.QFont.Weight.Normal)
        self.trans_table.setFont(data_font)

        self.trans_table.setColumnWidth(0, 150)
        self.trans_table.setColumnWidth(1, 220) 
        self.trans_table.setColumnWidth(2, 220)  
        self.trans_table.setColumnWidth(3, 130)  
        self.trans_table.setColumnWidth(4, 180)

        self.trans_table.verticalHeader().setVisible(False)

        self.print_trans_btn = QtWidgets.QPushButton(parent=self.transaction_frame)
        self.print_trans_btn.setGeometry(QtCore.QRect(400, 600, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(12)
        self.print_trans_btn.setFont(font)
        self.print_trans_btn.setObjectName("print_trans_btn")


        self.trans_option_box = QtWidgets.QComboBox(parent=self.transaction_frame)
        self.trans_option_box.setGeometry(QtCore.QRect(450, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(18)
        self.trans_option_box.setFont(font)
        self.trans_option_box.setObjectName("trans_option_box")
        

        BankSphere.setCentralWidget(self.centralwidget)

        BankSphere.setStyleSheet("""
            QMainWindow {
                background-color: white;
            }
            QWidget {
                background-color: white;
                color: black;
            }
            QFrame #tabs_frame{
                background-color: #EAEAEA;
                border-radius: 10px;
            }
            QLabel {
                background-color: white;
                color: black;
            }
            QPushButton {
                background-color: white;
                border: 1px solid black;
                padding: 5px;
                border-radius: 5px;
            }
            QPushButton:hover {
                background-color: #e0e0e0;
            }
            QHeaderView::section {
                background-color: #ffffff;  /* Change the background color */
                border: 1px solid #a0a0a0;  /* Set the border color */
                padding: 5px;                /* Add some padding */
            }
            QRadioButton {
                spacing: 5px;
            }
            QRadioButton::indicator {
                width: 15px;
                height: 15px;
                border-radius: 7px;
                border: 2px solid #555;
                background-color: #fff;
            }
            QRadioButton::indicator::unchecked {
                border: 2px solid #555;
                background-color: #fff;
            }
            QRadioButton::indicator::checked {
                border: 2px solid #555;
                background-color: #555;
            }
        """)

        self.retranslateUi(BankSphere)
        QtCore.QMetaObject.connectSlotsByName(BankSphere)

    def retranslateUi(self, BankSphere):
        _translate = QtCore.QCoreApplication.translate
        BankSphere.setWindowTitle(_translate("BankSphere", "BANKSPHERE"))
        self.main_label.setText(_translate("BankSphere", "BANKSPHERE"))
        self.sub_label.setText(_translate("BankSphere", "Your Financial World, Simplified."))
        self.username_label.setText(_translate("BankSphere", "Username: "))
        self.password_label.setText(_translate("BankSphere", "Password:"))
        self.login_btn.setText(_translate("BankSphere", "Login"))
        self.new_user_label.setText(_translate("BankSphere", "New User ?"))
        self.register_btn.setText(_translate("BankSphere", "Register"))
        self.label_1.setText(_translate("BankSphere", "BANKSPHERE"))
        self.sub_label_register.setText(_translate("BankSphere", "Your Financial World, Simplified."))
        self.label.setText(_translate("BankSphere", "First Name:"))
        self.label_2.setText(_translate("BankSphere", "Last Name:"))
        self.label_3.setText(_translate("BankSphere", "Date of Birth:"))
        self.label_4.setText(_translate("BankSphere", "Username:"))
        self.generate_username_btn.setText(_translate("BankSphere", "Generate"))
        self.label_5.setText(_translate("BankSphere", "Password:"))
        self.register_form_btn.setText(_translate("BankSphere", "Register"))
        self.main_label_logged.setText(_translate("BankSphere", "BANKSPHERE"))
        self.sub_label_logged.setText(_translate("BankSphere", "Your Financial World, Simplified."))
        self.acc_info_btn.setText(_translate("BankSphere", "Accounts Info"))
        self.transfer_btn.setText(_translate("BankSphere", "Transfer Funds"))
        self.transactionsbtn.setText(_translate("BankSphere", "Transactions"))
        self.add_mon_btn.setText(_translate("BankSphere", "Add Money"))
        self.profile_btn.setText(_translate("BankSphere", "Profile"))
        self.p_proicon.setText(_translate("BankSphere", "    PROFILE"))
        self.p_usn.setText(_translate("BankSphere", "USER NAME:"))
        self.p_fn.setText(_translate("BankSphere", "FIRST NAME:"))
        self.p_ln.setText(_translate("BankSphere", "LAST NAME:"))
        self.p_db.setText(_translate("BankSphere", "DOB:"))
        self.p_adr.setText(_translate("BankSphere", "ADDRESS:"))
        self.p_phnno.setText(_translate("BankSphere", "PHONE NUMBER:"))
        self.p_em.setText(_translate("BankSphere", "EMAIL:"))
        self.p_username.setText(_translate("BankSphere", "SAMPLE_USER_NAME"))
        self.p_firstname.setText(_translate("BankSphere", "SAMPLE_FIRST_NAME"))
        self.p_lastname.setText(_translate("BankSphere", "SAMPLE_LAST_NAME"))
        self.p_dob.setText(_translate("BankSphere", "SAMPLE_DOB"))
        self.p_address.setText(_translate("BankSphere", "SAMPLE_ADDRESS"))
        self.p_phonenum.setText(_translate("BankSphere", "SAMPLE_PHONE_NUMBER"))
        self.p_email.setText(_translate("BankSphere", "SAMPLE_EMAIL"))
        self.p_edit_profile_btn.setText(_translate("BankSphere", "Edit Profile"))
        self.tr_b.setText(_translate("BankSphere", "Select Bank:"))
        self.tr_cont.setText(_translate("BankSphere", "Continue"))
        self.tr_s.setText(_translate("BankSphere", "Sender\'s Account No: "))
        self.tr_r.setText(_translate("BankSphere", "Reciever\'s Account No: "))
        self.tr_a.setText(_translate("BankSphere", "Amount:"))
        self.tr_list_acc.setText(_translate("BankSphere", "List my Accounts"))
        self.trc_fr.setText(_translate("BankSphere", "From: "))
        self.trc_t.setText(_translate("BankSphere", "To:"))
        self.trc_a.setText(_translate("BankSphere", "Amount:"))
        self.trc_or.setText(_translate("BankSphere", "OR"))
        self.trc_cancel.setText(_translate("BankSphere", "Cancel"))
        self.trc_ep.setText(_translate("BankSphere", "Enter PIN:"))
        self.trc_verify.setText(_translate("BankSphere", "Verify"))
        self.tr_rec_sd.setText(_translate("BankSphere", "Your Payment is Successfully Done."))
        self.tr_rec_ti.setText(_translate("BankSphere", "Transaction Id :"))
        self.tr_rec_trans_id.setText(_translate("BankSphere", "1234567890"))
        self.tr_rec_print.setText(_translate("BankSphere", "Print Receipt"))
        self.tr_rec_home.setText(_translate("BankSphere", "Home"))
        self.ai_acc_labels.setText(_translate("BankSphere", "No Accounts Found"))
        self.ai_add_acc_btn.setText(_translate("BankSphere", "Add Account"))
        item = self.ai_table.horizontalHeaderItem(0)
        item.setText(_translate("BankSphere", "Bank"))
        item = self.ai_table.horizontalHeaderItem(1)
        item.setText(_translate("BankSphere", "Account Number"))
        item = self.ai_table.horizontalHeaderItem(2)
        item.setText(_translate("BankSphere", "Account Type"))
        item = self.ai_table.horizontalHeaderItem(3)
        item.setText(_translate("BankSphere", "Registered Name"))
        item = self.ai_table.horizontalHeaderItem(4)
        item.setText(_translate("BankSphere", "Created Date"))
        self.ai_check_bal_btn.setText(_translate("BankSphere", "Check Balance"))
        self.ai_cr_label.setText(_translate("BankSphere", "Add New Account"))
        self.ai_cr_b.setText(_translate("BankSphere", "Select Bank: "))
        self.ai_cr_at.setText(_translate("BankSphere", "Select Account Type:"))
        self.ai_cr_p.setText(_translate("BankSphere", "Create a 4 digit Pin:"))
        self.ai_cr_btn.setText(_translate("BankSphere", "Create"))
        self.ai_cbal_label.setText(_translate("BankSphere", "Check Account Balance"))
        self.ai_cbal_b.setText(_translate("BankSphere", "Select Bank: "))
        self.ai_cbal_an.setText(_translate("BankSphere", "Account Number:"))
        self.ai_cbal_list_acc.setText(_translate("BankSphere", "List Accounts"))
        self.ai_cbal_btn.setText(_translate("BankSphere", "Check Balance"))
        self.ai_cbal_cb.setText(_translate("BankSphere", "Current Balance:"))
        self.ai_cbal_bal.setText(_translate("BankSphere", ""))
        self.ai_cbal_p.setText(_translate("BankSphere", "Account Pin:"))
        self.admin_label.setText(_translate("BankSphere", "Admin Login"))
        self.admin_username.setText(_translate("BankSphere", "Username: "))
        self.admin_pass.setText(_translate("BankSphere", "Password:"))
        self.admin_login_btn.setText(_translate("BankSphere", "Login"))
        self.add_mon_lab.setText(_translate("BankSphere", "Add Money"))
        self.add_mon_sub.setText(_translate("BankSphere", "(For Demonstration Purposes)"))
        self.add_mon_b.setText(_translate("BankSphere", "Select Bank:"))
        self.add_mon_lis_acc.setText(_translate("BankSphere", "List all Accounts"))
        self.add_mon_acc.setText(_translate("BankSphere", "Account Number:"))
        self.add_mon_am.setText(_translate("BankSphere", "Amount to Add:"))
        self.add_mon_add_btn.setText(_translate("BankSphere", "Add Amount"))
        self.trans_bank_opt.setText(_translate("BankSphere", "Specific Bank"))
        self.trans_accnum_opt.setText(_translate("BankSphere", "Specific Account Number"))
        self.trans_all_opt.setText(_translate("BankSphere", "All"))
        self.trans_retrive_tbn.setText(_translate("BankSphere", "Retrive Transactions"))
        self.print_trans_btn.setText(_translate("BankSphere", "Print PassBook"))
        item = self.trans_table.horizontalHeaderItem(0)
        item.setText(_translate("BankSphere", "Transaction Id"))
        item = self.trans_table.horizontalHeaderItem(1)
        item.setText(_translate("BankSphere", "Sender"))
        item = self.trans_table.horizontalHeaderItem(2)
        item.setText(_translate("BankSphere", "Reciever"))
        item = self.trans_table.horizontalHeaderItem(3)
        item.setText(_translate("BankSphere", "Amount"))
        item = self.trans_table.horizontalHeaderItem(4)
        item.setText(_translate("BankSphere", "DateTime"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BankSphere = QtWidgets.QMainWindow()
    ui = Ui_BankSphere()
    ui.setupUi(BankSphere)
    BankSphere.show()
    sys.exit(app.exec())
